version: "3.9"  # optional since v1.27.0
services:
  wal2json-docker-local:
    build: ./pg-wal2json
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
